kind: live
name: Run Jupyter notebook
author: Alexey Naiden
descr: runs Jupyter notebook with your image and opens it in default web browser

inputs:
  volumes_data_remote:
    descr: reference to a data volume
  volumes_common_data_remote:
    descr: reference to a common data volume
  volumes_code_remote:
    descr: reference to a code volume
  volumes_config_remote:
    descr: reference to a config volume
  volumes_notebooks_remote:
    descr: reference to a notebooks volume
  volumes_results_remote:
    descr: reference to a results volume
  jupyter_mode:
    descr: The mode in which to run Jupyter, 'notebook' or 'lab'
    default: "notebook"
  job_name:
    descr: Predictible subdomain name, which replaces JobID in the full job URI
    default: ""
  image:
    descr: image name used to run Jupyter, make sure it is installed
    default: "neuromation/base:latest"
  preset:
    descr: resource preset to use, when running the jupyter job
    default: ""
  multi_args:
    descr: additional arguments
    default: ""
  http_port:
    descr: http port for jupyter
    default: "8888"
  http_auth:
    descr: whether to use http auth for jupter
    default: "True"
  cull_idle_timeout:
    descr: timeout in seconds after which the idle kernel will be killed
    default: "7200"

job:
    multi: True
    image: ${{ inputs.image }}
    name: ${{ inputs.job_name }}
    preset: ${{ inputs.preset }}
    http_port: ${{ inputs.http_port }}
    http_auth: ${{ inputs.http_auth }}
    browse: True
    detach: True
    volumes:
      - "${{ inputs.volumes_data_remote }}:/project/data:rw"
      - "${{ inputs.volumes_common_data_remote }}:/project/common_data:rw"
      - "${{ inputs.volumes_code_remote }}:/project/modules:rw"
      - "${{ inputs.volumes_config_remote }}:/project/config:rw"
      - "${{ inputs.volumes_notebooks_remote }}:/project/notebooks:rw"
      - "${{ inputs.volumes_results_remote }}:/project/results:rw"
    env:
      PYTHONPATH: /project/modules
    cmd: >-
      jupyter ${{ inputs.jupyter_mode }} ${{ inputs.multi_args }}
        --no-browser
        --ip=0.0.0.0
        --port=${{ inputs.http_port }}
        --allow-root
        --NotebookApp.token=
        --notebook-dir=/project/notebooks
        --NotebookApp.shutdown_no_activity_timeout=${{ 0 if int(inputs.cull_idle_timeout) == 0 else 900}}
        --MappingKernelManager.cull_idle_timeout=${{ inputs.cull_idle_timeout }}
        --MappingKernelManager.cull_connected=True
